# Generated by Django 3.2.9 on 2021-11-04 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(default='profile1.png', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('age', models.CharField(max_length=5, null=True)),
                ('gender', models.ImageField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True, upload_to='')),
                ('cnic', models.CharField(max_length=200, null=True)),
                ('cnic_img', models.ImageField(null=True, upload_to='')),
                ('qualification', models.CharField(max_length=100, null=True)),
                ('qualification_img', models.ImageField(null=True, upload_to='')),
                ('qualification_year', models.CharField(max_length=100, null=True)),
                ('qualification_institute', models.CharField(max_length=100, null=True)),
                ('emp_status', models.CharField(choices=[('Govt. Employee', 'Govt. Employee'), ('Un-Employed', 'Un-Employed'), ('Private Job', 'Private Job')], max_length=200, null=True)),
                ('emp_designation', models.CharField(blank=True, max_length=200, null=True)),
                ('emp_bps', models.CharField(blank=True, max_length=200, null=True)),
                ('emp_home_address', models.CharField(max_length=200, null=True)),
                ('emp_institute_address', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200, null=True)),
                ('exam_year', models.CharField(max_length=200, null=True)),
                ('exam_starting_date', models.CharField(max_length=200, null=True)),
                ('exam_ending_date', models.CharField(max_length=200, null=True)),
                ('exam_type', models.CharField(choices=[('Annual', 'Annual'), ('Semester', 'Semester'), ('Term', 'Term')], max_length=200, null=True)),
                ('exam_last_date', models.CharField(max_length=200, null=True)),
                ('exam_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('datesheet_img', models.ImageField(blank=True, default='profile1.png', null=True, upload_to='')),
                ('cities', models.ManyToManyField(to='supervisory.City')),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostelName', models.CharField(max_length=200, null=True)),
                ('hostelRooms', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('duty_as', models.CharField(choices=[('Superintendent', 'Superintendent'), ('Dy. Superintendent', 'Dy. Superintendent'), ('Add. Dy. Superintendent', 'Add. Dy. Superintendent'), ('Invigilator', 'Invigilator')], max_length=200, null=True)),
                ('duty_status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Denied', 'Denied')], max_length=200, null=True)),
                ('note', models.CharField(max_length=1000, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervisory.customer')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervisory.exams')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomName', models.CharField(max_length=200, null=True)),
                ('roomCapacity', models.CharField(max_length=200, null=True)),
                ('roomFee', models.CharField(max_length=200, null=True)),
                ('rHostelName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervisory.hostel')),
            ],
        ),
    ]
