# Generated by Django 3.2.9 on 2021-11-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisory', '0002_hostelapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelapply',
            name='duration',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
