# Generated by Django 3.2.9 on 2021-11-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisory', '0004_auto_20211105_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='roomStatus',
        ),
        migrations.AddField(
            model_name='hostelapply',
            name='roomStatus',
            field=models.CharField(choices=[('Vacant', 'Vacant'), ('Occupied', 'Occupied')], max_length=200, null=True),
        ),
    ]
