# Generated by Django 3.2.9 on 2021-11-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisory', '0005_auto_20211105_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelapply',
            name='roomStatus',
        ),
    ]
