# Generated by Django 3.2.9 on 2021-11-06 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervisory', '0006_remove_hostelapply_roomstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelapply',
            name='app_status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Denied', 'Denied')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hostelapply',
            name='rooms',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supervisory.rooms'),
        ),
    ]
