# Generated by Django 3.2.9 on 2021-11-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisory', '0007_auto_20211106_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelapply',
            name='feeStatus',
            field=models.CharField(choices=[('Paid', 'Paid'), ('UnPaid', 'UnPaid')], max_length=200, null=True),
        ),
    ]
