# Generated by Django 3.2.9 on 2021-11-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisory', '0009_auto_20211107_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelapply',
            name='upload_challan',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
