# Generated by Django 3.2.9 on 2021-11-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisory', '0010_alter_hostelapply_upload_challan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messName', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
