# Generated by Django 3.2.9 on 2021-11-07 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisory', '0012_mess_rhostelname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mess',
            old_name='rHostelName',
            new_name='mHostelName',
        ),
    ]
