# Generated by Django 3.2.9 on 2021-11-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisory', '0013_rename_rhostelname_mess_mhostelname'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelapply',
            name='date_due',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
