# Generated by Django 3.2.9 on 2021-11-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisory', '0014_hostelapply_date_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelapply',
            name='ac',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hostelapply',
            name='mess',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Mess',
        ),
    ]
