# Generated by Django 3.2.9 on 2021-11-09 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisory', '0016_auto_20211109_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exams',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='userapply',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='userapply',
            name='exam',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Exams',
        ),
        migrations.DeleteModel(
            name='UserApply',
        ),
    ]
